version: '3.8'
services:
    postgres:
      image: postgres:15
      environment:
        POSTGRES_DB: code_review_agent
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      ports:
        - "5432:5432"  # <- PostgreSQL ports here
    redis:
      image: redis:7-alpine
      ports:
        - "6379:6379"      # <- Redis ports here